Console.WriteLine("Дарова бандит. Говорят ты не можешь посчитать 1 + 1?");
Console.WriteLine("Ну, так и быть я тебе помогу. Смотри, ля как могу");
int Number1 = new Random().Next(1,10);
int Number2 = new Random().Next(1,10);
Console.Write("Первое число ");
Console.WriteLine(Number1);
Console.Write("Второе число ");
Console.WriteLine(Number2);
int Sum =  Number1 + Number2;
Console.Write("Сумма ");
Console.WriteLine(Sum);
